version: "3.7"

services:
  php:
    build:
      context: ./
      dockerfile: docker/php/Dockerfile
      args:
        TIMEZONE: ${TIMEZONE}
        PHP_VERSION: ${PHP_VERSION}
        NODE_VERSION: ${NODE_VERSION}
        APP_GROUP_NAME: ${APP_GROUP_NAME}
        APP_GROUP_ID: ${APP_GROUP_ID}
        PHP_SOCKET_DIR: ${PHP_SOCKET_DIR}
        PHP_SOCKET_FILE: ${PHP_SOCKET_FILE}
    container_name: "${APP_NAME}_php"
    restart: always
    volumes:
      - ./app:${APP_CODE_DIR}
      - socket:${PHP_SOCKET_DIR}
      - ./docker/php/custom.ini:/usr/local/etc/php/conf.d/custom.ini:cached
    labels:
      - "traefik.enable=false"
    networks:
      - nginx
      - private
 
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/Dockerfile
      args:
        DOMAIN: ${DOMAIN}
        FRONTEND_NGINX_PORT: ${FRONTEND_NGINX_PORT}
        BACKEND_NGINX_PORT: ${BACKEND_NGINX_PORT}
        NGINX_CODE_DIR: ${NGINX_CODE_DIR}
        APP_GROUP_NAME: ${APP_GROUP_NAME}
        APP_GROUP_ID: ${APP_GROUP_ID}
        PHP_SOCKET_DIR: ${PHP_SOCKET_DIR}
        PHP_SOCKET_FILE: ${PHP_SOCKET_FILE}
    container_name: "${APP_NAME}_nginx"
    restart: always
    volumes:
      - socket:${PHP_SOCKET_DIR}
      - ./data/logs/:/var/log/nginx
      - ./docker/nginx/ssl/${DOMAIN}.crt:/etc/nginx/ssl/${DOMAIN}.crt
      - ./docker/nginx/ssl/${DOMAIN}.key:/etc/nginx/ssl/${DOMAIN}.key
    depends_on:
      - php
    expose:
      - ${FRONTEND_NGINX_PORT}
      - ${BACKEND_NGINX_PORT}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.frontend.rule=${APP_NAME}"
      - "traefik.port=80"
      # WEB
      - "traefik.http.services.${APP_NAME}.loadbalancer.server.port=80"
      - "traefik.http.routers.${APP_NAME}.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}.entrypoints=web"
      - "traefik.http.routers.${APP_NAME}.tls=false"
      # WEB SECURE
      - "traefik.tcp.routers.${APP_NAME}.entrypoints=websecure"
      - "traefik.tcp.routers.${APP_NAME}.rule=HostSNI(`${DOMAIN}`)"
      - "traefik.tcp.routers.${APP_NAME}.service=${APP_NAME}"
      - "traefik.tcp.routers.${APP_NAME}.tls.DOMAINs[0].main=${DOMAIN}"
      - "traefik.tcp.routers.${APP_NAME}.tls=true"
      - "traefik.tcp.routers.${APP_NAME}.tls.passthrough=true"
      - "traefik.tcp.services.${APP_NAME}.loadbalancer.server.port=443"
    networks:
      - nginx
      - public
      - private

  db:
    image: mariadb:latest
    container_name: ${APP_NAME}_db
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql:delegated
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    labels:
      - "traefik.enable=false"
    networks:
      - private
  
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: ${APP_NAME}_pma
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${APP_NAME}_db
      #- PMA_USER=${MYSQL_USER}
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQL_ROOT_PASSWORD}
      #- PMA_PASSWORD=${MYSQL_PASSWORD}
      - UPLOAD_LIMIT=1G
    restart: always
    volumes:
      - ./docker/phpmyadmin/custom.ini:/usr/local/etc/php/conf.d/custom.ini
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.frontend.rule=${APP_NAME}-pma"
      - "traefik.port=8080"
      # WEB 
      - "traefik.http.services.${APP_NAME}-pma.loadbalancer.server.port=80"
      - "traefik.http.routers.${APP_NAME}-pma.rule=Host(`pma.${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-pma.entrypoints=web"
      - "traefik.http.routers.${APP_NAME}-pma.tls=false"
    networks:
      - public
      - private

  redis:
    image: redis:latest
    command: ["redis-server", "--appendonly", "yes"]
    container_name: "${APP_NAME}_redis"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    labels:
      - "traefik.enable=false"
    networks:
      - private


  mongo:
    image: 'mongo:latest'
    container_name: "${APP_NAME}_mongo"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./data/mongodb/data:/data/db:cached
    ports:
      - 27017:27017
    networks:
      - public
      - private

  me:
    image: 'mongo-express'
    container_name: ${APP_NAME}_me
    restart: always
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MYSQL_ROOT_PASSWORD}
      ME_CONFIG_OPTIONS_EDITORTHEME: 'ambiance'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=public"
      - "traefik.frontend.rule=${APP_NAME}-me"
      - "traefik.port=80"
      # WEB 
      - "traefik.http.services.${APP_NAME}-me.loadbalancer.server.port=8081"
      - "traefik.http.routers.${APP_NAME}-me.rule=Host(`me.${DOMAIN}`)"
      - "traefik.http.routers.${APP_NAME}-me.tls=false"
    networks: 
      - public
      - private
    depends_on:
      - mongo

  rabbitmq:
    image: rabbitmq:3.7.5-management
    container_name: ${APP_NAME}_ra
    hostname: rabbitmq
    user: rabbitmq
    volumes:
      - "traefik.http.services.${APP_NAME}-tr.loadbalancer.server.port=80"
      - "traefik.docker.network=public"
      - "traefik.http.routers.${APP_NAME}-tr.rule=Host(`ra.${DOMAIN}`)"
      - ./data/rabbitmq:/var/lib/rabbitmq/mnesia/rabbit@app-rabbitmq:cached
    environment:
        RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
        RABBITMQ_DEFAULT_USER: rabbitmq
        RABBITMQ_DEFAULT_PASS: rabbitmq
        RABBITMQ_DEFAULT_VHOST: /
    networks:
      - public
      - private

  languagetool:
    image: 'silviof/docker-languagetool'
    container_name: "${APP_NAME}_lang"
    restart: always
    networks:
      - private

networks:
  public:
    external: true
  nginx:
    external: true
  private:
    internal: true

volumes:
  socket:
